### ISSUE TITLE
Error after upgrade Room library version to 2.5.0

### ISSUE THREAD

**Issue by Nataliya-Mokretsova** [mindbox-cloud/android-sdk#299]
I updated version of Room library in app to 2.5.0 and now app crashes
```
E/Mindbox: Mindbox monitoring caught unhandled error
    java.lang.NoSuchFieldError: No instance field mDelegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/~~HDPt9EWxz_YZ2pxNIF0btw...base.apk!classes20.dex)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(Unknown Source:4)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:52)
        at cloud.mindbox.mobile_sdk.monitoring.data.room.dao.MonitoringDao_Impl$5.call(MonitoringDao_Impl.java:96)
        at cloud.mindbox.mobile_sdk.monitoring.data.room.dao.MonitoringDao_Impl$5.call(MonitoringDao_Impl.java:93)
        at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.room.TransactionExecutor.execute$lambda$1$lambda$0(TransactionExecutor.kt:36)
        at androidx.room.TransactionExecutor.$r8$lambda$AympDHYBb78s7_N_9gRsXF0sHiw(Unknown Source:0)
        at androidx.room.TransactionExecutor$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by vorobalek** [comment]
@Nataliya-Mokretsova 
I have found the same issue [here](https://issuetracker.google.com/issues/267058486). Probably, it might be helpful. Also, I would like to ask you for a sort of reproduction steps.

**Comment by vorobalek** [comment]
@Nataliya-Mokretsova, this issue will be closed tomorrow because I haven't heard back from you yet.

**Comment by Nataliya-Mokretsova** [comment]
Steps to reproduce:
1. Upgrade androidx.room:room version to 2.5.0.
2. Install the application into device/emulator and run it
3. The app crashes

**Comment by vorobalek** [comment]
@Nataliya-Mokretsova,

Unfortunately, we did not succeed in reproducing this error in our engineering testing application. Please, taking into account [another similar issue](https://issuetracker.google.com/issues/265824784), recheck your application's source code.
